In [63]:
import torch

In [64]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y = torch.tensor([0,1,2,2,1])

In [73]:
print(y.unsqueeze(1))

tensor([[0],
        [1],
        [2],
        [2],
        [1]])


In [76]:
print(x * torch.scatter(input=torch.zeros_like(x),index=y.unsqueeze(1),value=1,dim=1))

tensor([[ 1,  0,  0],
        [ 0,  5,  0],
        [ 0,  0,  9],
        [ 0,  0, 12],
        [ 0, 14,  0]])


In [75]:
input = torch.zeros_like(x)
indices = y
print(input.scatter(1, indices.unsqueeze(1), 1))
print(torch.scatter(input,1, indices.unsqueeze(1), 1))

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]])


In [65]:
torch.zeros_like(x)
torch.tensor([[y[i]] for i in range(len(y))])

tensor([[0],
        [1],
        [2],
        [2],
        [1]])

In [66]:
print( x * torch.scatter(input=torch.zeros_like(x),index=torch.tensor([[y[i]] for i in range(len(y))]),src=torch.ones_like(x),dim=0))

tensor([[1, 0, 0],
        [4, 0, 0],
        [7, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
help(torch.scatter)

Help on built-in function scatter in module torch:

scatter(...)
    scatter(input, dim, index, src) -> Tensor
    
    Out-of-place version of :meth:`torch.Tensor.scatter_`



In [44]:
label = [1,2,3,3,3,3]
# target = torch.tensor([
#     [0,1,0,0],
#     [0,0,1,0],
#     [0,0,0,1],
#     [0,0,0,1],
#     [0,0,0,1],
#     [0,0,0,1],
# ]
# )
num_labels = 4

In [45]:
index = torch.tensor([[i,label[i]] for i in range(len(label))])
print(index)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 3],
        [4, 3],
        [5, 3]])


In [46]:
print(torch.ones([len(label),num_labels]))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [47]:
ans = torch.scatter(input=torch.zeros([len(label),num_labels]),src=torch.ones([len(label),num_labels]),dim=0,index=index)

In [48]:
ans

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]])

In [1]:
print(len([8012, 2545, 2780,  240, 9500, 2233, 6575, 5224,  177, 9603, 7785, 4701,
        3551, 5307, 2721, 9734, 6755, 2445,  252, 3940, 8907, 8438, 1567, 9247,
         727, 9998, 8087, 9121, 8493, 6755, 3009, 7372,  358, 5019, 9495, 8347,
        6279,  375, 4964,  250, 9416, 5380, 1229, 9378, 8034, 9906, 8741, 8433,
        5872, 4723,  223, 8425, 7141, 1703, 5907, 4647, 1021,  380, 5148, 6026,
        5960, 5031, 5928, 7569, 2050, 6242, 7308, 9041, 8111, 4855, 6320, 1387,
        6170, 1924, 5009, 6580, 7173, 4786, 5468, 6014, 6659, 3645, 6027, 9054,
        8179, 4422, 7928, 3566, 7730,  741, 6800, 3813, 6257, 9007, 4391,  169,
        7934, 3402, 8963, 4747,   18, 9149, 6794, 3811, 6735, 1502, 3533, 7624,
        6326, 3615, 5452,  206, 7224, 7920, 8997, 6389, 3247, 4778,  885, 2091,
        3161, 8844,   36, 8176, 3432, 1386, 9514, 9693, 1041, 6616, 2003, 4882,
        3911, 7356, 3721,  937, 2724, 2819, 1895, 2582, 5961, 4099, 9938,  793,
        6726, 9895, 2646, 8601, 2370, 7740, 3117, 1191, 1354, 5130, 4818, 3549,
        9440, 6587, 6289,  104, 6852, 2259, 2153, 8669, 5305, 2091, 9899, 7195,
        4073, 3440, 2732, 2979, 1669, 4926, 8988, 3099, 4939, 5870, 8711,  996,
        4402,  513, 3692, 8672,  876, 2470, 3559, 2397, 6246, 6658, 4074, 1204,
         705, 3881, 6404, 3748, 5043, 5055, 7612, 2376, 5737, 5528, 8687,   16,
        2915, 8836, 6254, 1868, 2410,    8, 9241, 3181,  738, 3782, 7317, 2637,
        7123, 4601, 9959, 6053, 9245,  327, 5615, 1684,  742, 4645, 9927, 2065,
        6718, 6242, 6911, 3145,  541, 2181, 1229, 6476, 2928, 5309, 4454,  653,
        2927, 6181, 2375, 8806, 6523, 8459,  268, 1310,  448, 2985, 9660, 1718,
        3116, 3596,  685, 4461]))

256
