In [63]:
import torch

In [64]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y = torch.tensor([0,1,2,2,1])

In [73]:
print(y.unsqueeze(1))

tensor([[0],
        [1],
        [2],
        [2],
        [1]])


In [76]:
print(x * torch.scatter(input=torch.zeros_like(x),index=y.unsqueeze(1),value=1,dim=1))

tensor([[ 1,  0,  0],
        [ 0,  5,  0],
        [ 0,  0,  9],
        [ 0,  0, 12],
        [ 0, 14,  0]])


In [75]:
input = torch.zeros_like(x)
indices = y
print(input.scatter(1, indices.unsqueeze(1), 1))
print(torch.scatter(input,1, indices.unsqueeze(1), 1))

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]])
tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]])


In [65]:
torch.zeros_like(x)
torch.tensor([[y[i]] for i in range(len(y))])

tensor([[0],
        [1],
        [2],
        [2],
        [1]])

In [66]:
print( x * torch.scatter(input=torch.zeros_like(x),index=torch.tensor([[y[i]] for i in range(len(y))]),src=torch.ones_like(x),dim=0))

tensor([[1, 0, 0],
        [4, 0, 0],
        [7, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [4]:
help(torch.scatter)

Help on built-in function scatter in module torch:

scatter(...)
    scatter(input, dim, index, src) -> Tensor
    
    Out-of-place version of :meth:`torch.Tensor.scatter_`



In [44]:
label = [1,2,3,3,3,3]
# target = torch.tensor([
#     [0,1,0,0],
#     [0,0,1,0],
#     [0,0,0,1],
#     [0,0,0,1],
#     [0,0,0,1],
#     [0,0,0,1],
# ]
# )
num_labels = 4

In [45]:
index = torch.tensor([[i,label[i]] for i in range(len(label))])
print(index)

tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 3],
        [4, 3],
        [5, 3]])


In [46]:
print(torch.ones([len(label),num_labels]))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [47]:
ans = torch.scatter(input=torch.zeros([len(label),num_labels]),src=torch.ones([len(label),num_labels]),dim=0,index=index)

In [48]:
ans

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]])